version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:5000
        - NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=safcajaf
        - NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET=techarcade_preset
    ports:
      - "3000:3000"
